### ISSUE TITLE
Change TestRunner

### ISSUE THREAD

**Issue by texttechne** [cpro-js/ui5-mobx#5]
Use [ui5-test-runner](https://github.com/ArnaudBuchholz/ui5-test-runner) instead of Karma (already outdated).

[Marians spreadsheet importer](https://github.com/marianfoo/ui5-cc-spreadsheetimporter) should serve as example.

**Comment by texttechne** [comment]
@wridgeu this looks more complicated than just exchanging ui5-test-runner for karma... it seems to me that it is assumed that we have a complete webapp...

**Comment by wridgeu** [comment]
Hey @texttechne, you're right.

Seems like the [ui5-test-runner](https://github.com/ArnaudBuchholz/ui5-test-runner) fulfills a specific purpose in replacing the [karma-ui5](https://github.com/SAP/karma-ui5) plugin and helps you get rid of karma in your UI5 **application**.

I've checked with Marians [packages](https://github.com/marianfoo/ui5-cc-spreadsheetimporter/tree/main/packages) and the standalone tests for his custom components are done in other test runners/frameworks like f.e. [mocha](https://mochajs.org/).

Do you have a preferred, alternative, test-runner in mind?

**Comment by texttechne** [comment]
Mocha would be nice and shouldn't have that much overhead as Karma.

**Comment by texttechne** [comment]
@wridgeu If you want to tackle any issue than please assign yourself. I will do the same...

**Comment by wridgeu** [comment]
Hi @texttechne, I think this topic should be either put on the back-burner or even closed for now. I've looked around and didn't find any "great" (easy to use while being low on maintenance effort) alternative for Karma so far. The [best practice ts library showcase](https://github.com/SAP-samples/ui5-typescript-control-library) (though being for a control library) also continues making use of Karma.

I did have a brief look into 
- [mocha](https://mochajs.org/)
- [jasmine](https://jasmine.github.io/)
- [web-test-runner](https://modern-web.dev/docs/test-runner/overview/)
- [playwright](https://playwright.dev/)
- [wdi5](https://ui5-community.github.io/wdi5/#/)

or vdom alternatives like (though due to vdom mostly out of the question in general - but could work in our use-case)
- [jest](https://jestjs.io/)
- [vitest](https://vitest.dev/)

[Karma](https://karma-runner.github.io/latest/index.html) with the addition of [karma-ui5](https://github.com/SAP/karma-ui5) currently has the big advantage of actively using the UI5 tooling in the background and therefore making it easy to combine the typescript files and resolving the required UI5 dependencies.

## Problems 

When I looked into the above mentioned tools/runners, there were always two issues:

- The very first problem was resolving the typescript path alias configured in the `tsconfig` but this one you can get out of the way quite quickly for each of them. 
- Where I didn't really know how to proceed and which made me stop looking into it for now was: when the test files required UI5 dependencies like f.e. `sap/ui/model/Context` they cannot be resolved. This is usually done by the tooling as it is also responsible to manage those dependencies. When used with karma they're loaded into the abstract file system and served together with the resources in question and can then be resolved properly. This is something of course none of the tools are capable of out of the box.

### Workarounds?

The way I see it, there would be too much to workaround in the sense of: including more dependencies and trying to make things work somehow. I think one can maybe make it work with mocha or jasmine by introducing some more custom steps and trying to take care of resolving the UI5 dependencies accordingly (something along the lines of custom UI5 cdn in index.html + transpiling the tests accordingly.. or custom implementing what karma-ui5 does under the hood) _but I didn't go that deep_. 

### Well that didn't work ...

You definitely cannot manually consume the UI5 dependencies in the project, as the UI5 tooling then won't work anymore so nothing along the lines of manually resolving to [sap.ui.core](https://www.npmjs.com/package/@openui5/sap.ui.core) as actual dependency in `package.json`.

### wdi5

I also had a quick [chat with Volker](https://twitter.com/vobu/status/1681369891905970176?s=20) regarding the use of wdi5 here and sadly you cannot make use of it as sole test runner for a standalone library project. You'd need a minimum UI5 application that consumes the library. So could of course be used with/for https://github.com/cpro-js/ui5-mobx/issues/6.

**Disclaimer**
Though I did spend some time on it and learned a few things here and there, I think I only scratched the surface and might've misunderstood or overlooked some things, I do tend to think too complex ^^. You might have a completely different view on this and more experience when it comes to UI5 deps resolving. I'm happy to stand and be corrected. :)

**Comment by texttechne** [comment]
Hi @wridgeu,

then, by all means, let's leave it that way. As you say, it's not worth the effort. Also, it works with Karma.

Thanks for the effort and the thorough investigation!
